name: build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Transpile check
        run: npm run check
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: welcome-banner-tgz
          path: '*.tgz'
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: '*.tgz'
